const route = require('express').Router()
const mongoose=require('mongoose')
const nodeMailer=require('nodemailer')

const application=mongoose.model('application')
const user_document_relation=mongoose.model('userdocumentrelation')

route.post('/',(req,res)=>{
    application.findOne({email:req.body.Email})
    .then((user)=>{
        if(user){
user.status='Rejected'
user.save()
.then((sv)=>{
    if(sv){
        let transporter = nodeMailer.createTransport({
            host: 'smtp.gmail.com',
            port: 465,
            secure: true,
            auth: {
                // should be replaced with real sender's account
                user: 'nekkunjpilani@gmail.com',
                pass: 'nikunj24'
            }
         });
         const html=`
         Sorry your application has been rejected due to some error,now you have to fill up the application again on
         <br>
         <a href="http://localhost:7007/en/online_application">Application Form</a>
         <br>
         You can also check your status on <br>
         <a href="http://localhost:7007/dashboard">Status Page</a><br>
         This is an autogenerated email <br> Do not contact through this email
         `
         let mailOptions = {
            // should be replaced with real recipient's account
            to: req.body.Email,
            subject: 'Application Rejected',
            html:html,
            text:html
         };
         transporter.sendMail(mailOptions, (error, info) => {
            if (error) {
                return console.log(error);
            }
            console.log('Message %s sent: %s', info.messageId, info.response);
            
         });
        }
})
.catch(err=>{console.log(err)})

        }
    })
    .catch(err=>{console.log(err)})
  });

  route.post('/document',(req,res)=>{
    user_document_relation.findOne({email:req.body.Email})
    .then((user)=>{
        if(user){
user.document_status='Rejected'
user.save()
.then((sv)=>{
    if(sv){
        let transporter = nodeMailer.createTransport({
            host: 'smtp.gmail.com',
            port: 465,
            secure: true,
            auth: {
                // should be replaced with real sender's account
                user: 'nekkunjpilani@gmail.com',
                pass: 'nikunj24'
            }
         });
         const html=`
         Sorry your documents have been rejected due to some error,now you can change the documents on
         <br>
         <a href="http://localhost:7007/upload_documents">Upload Documents</a>
         <br>
         You can also check your status on <br>
         <a href="http://localhost:7007/dashboard">Status Page</a><br>
         This is an autogenerated email <br> Do not contact through this email
         `
         let mailOptions = {
            // should be replaced with real recipient's account
            to: req.body.Email,
            subject: 'Your documents are rejected',
            html:html,
            text:html
         };
         transporter.sendMail(mailOptions, (error, info) => {
            if (error) {
                return console.log(error);
            }
            console.log('Message %s sent: %s', info.messageId, info.response);
            
         });    
        }
})
.catch(err=>{console.log(err)})
        }
    })
    .catch(err=>{console.log(err)})
  });
exports=module.exports={
    route
}